before_install:
   - nvm install 0.10
install:
  - tools/travis/setup-$TEST_SUITE
cache:
  - apt: false
  - directories:
    - /srv/phantomjs
env:
  - TEST_SUITE=frontend
  - TEST_SUITE=backend
  - TEST_SUITE=production
  - TEST_SUITE=py3k
language: python
python:
  - "2.7"
# command to run tests
script:
  - ./tools/travis/$TEST_SUITE
sudo: required
services:
- docker
addons:
  postgresql: "9.3"
