dist: trusty
before_install:
   - nvm install 0.10
install:
  - pip install coveralls
  - tools/travis/setup-$TEST_SUITE
  - tools/clean-venv-cache --travis
cache:
  - apt: false
  - directories:
    - $HOME/phantomjs
    - $HOME/zulip-venv-cache
    - node_modules
    - $HOME/node
env:
  global:
    - COVERALLS_PARALLEL=true
    - COVERALLS_SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=hnXUEBKsORKHc8xIENGs9JjktlTb2HKlG
    - BOTO_CONFIG=/tmp/nowhere
  matrix:
    - TEST_SUITE=frontend
    - TEST_SUITE=backend
language: python
python:
  - "2.7"
  - "3.4"
matrix:
  include:
    - python: "3.4"
      env: TEST_SUITE=static-analysis
    - python: "2.7"
      env: TEST_SUITE=production
      sudo: required
# command to run tests
script:
  - unset GEM_PATH
  - ./tools/travis/$TEST_SUITE
sudo: required
services:
- docker
addons:
  postgresql: "9.3"
after_success:
  coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
