install:
  - tools/travis/setup-$TEST_SUITE
cache:
  - apt: false
env:
  - TEST_SUITE=frontend
  - TEST_SUITE=backend
  - TEST_SUITE=production
language: python
python:
  - "2.7"
# command to run tests
script:
  - ./tools/travis/$TEST_SUITE
sudo: required
services:
- docker
addons:
  postgresql: "9.3"
