---
graphiti_base_url: https://stats1.zulip.net/graphiti/
graphite_base_url: https://graphiti:xxxxxxxxxxxxxxxxxx@stats1.zulip.net:444/
graphite_userpw: "graphiti:xxxxxxxxxxxxxxxxxx"
graphite_auth: :digest
graphite_cert: "/home/zulip/graphiti/humbughq_cert_internal.pem"
#graphite_base_url: https://user:pass@graphite01.pp.local
redis_url: localhost:6978:1/graphiti
tmp_dir: /tmp
fonts:
  - DroidSans
  - DejaVuSans
auto_refresh:
  enabled: true # checked by default?
  interval: 120 # seconds
default_options:
  title: "New Graph"
  from: -7d
  font: DroidSans
  fontSize: 10
  thickness: 2
  bgcolor: "#FFFFFF"
  fgcolor: "#333333"
  majorGridLineColor: "#ADADAD"
  minorGridLineColor: "#E5E5E5"
default_metrics:
  - "stats.foobar"
metric_prefix: "stats"
# Configure a service for snapshoting graphs. Current options are
# s3 (amazon s3) and fs (filesystem)
snapshots:
  # for s3 you need to provide `bucket`, `access_key_id`, and `secret_access_key`
  #
  # service: s3
  # bucket: mysnapshots
  # access_key_id: BLAH
  # secret_access_key: BLAHBLAH

  # for local filesystem you need to provide a dir to save the images
  # and the public route to that dir
  #
  # service: fs
  # dir: public/storage
  # public_host: http://graphiti.local/storage

# These are options that are passed to Pony
# https://github.com/benprew/pony
# in `to:` SLUG gets replaced with the slug of the dashboard being sent
reports:
  from: "Stampy <stampy@paperlesspost.com>"
  to: "graphiti+SLUG@paperlesspost.com"
  via: smtp
  via_options:
    address: 'smtp.gmail.com'
    port: 587
    authentication: plain
    enable_starttls_auto: true,
    user_name: "stampy@paperlesspost.com"
    password: "PASSWORD"
snapshots:
  service: none
