name: Legacy OS

on: [push, pull_request]

jobs:
  xenial:
    name: Ubuntu 16.04 Xenial (Python 3.5, legacy)
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Check tools/provision error message on xenial
        run: |
          { { ! tools/provision 2>&1 >&3; } | tee provision.err; } 3>&1 >&2
          grep -Fqx 'Error: ubuntu 16.04 is no longer a supported platform for Zulip.' provision.err
      - name: Check scripts/lib/upgrade-zulip-stage-2 error message on xenial
        run: |
          { { ! sudo scripts/lib/upgrade-zulip-stage-2 2>&1 >&3; } | tee upgrade.err; } 3>&1 >&2
          grep -Fq 'upgrade-zulip-stage-2: Unsupported platform: ubuntu 16.04' upgrade.err

      - name: Report status
        if: failure()
        env:
          ZULIP_BOT_KEY: ${{ secrets.ZULIP_BOT_KEY }}
        run: tools/ci/send-failure-message
